"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import HeaderWrapper from "@/components/layouts/HeaderWrapper";
import { HeaderSectionProvider } from "@/components/contexts/HeaderSectionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderSectionProvider>
          <HeaderWrapper />
          <Header />
          <div className="max-w-screen-xl mx-auto px-4">{children}</div>
          {/* Footer en pleine largeur */}
          <Footer />
        </HeaderSectionProvider>
      </body>
    </html>
  );
}
